// Det unauthorised edits to the vendored trees.
//
// vendor/ must stay a verbatim copy of upstream plus exactly two mechanical
// rewrites (package identity and `package:` imports). Laya named fork drift the
// top risk in this plan, so divergence has to be visible rather than silent.
//
// This tool records a SHA-256 baseline of every vendored source file at vendor
// time and verifies it on demand. Any file whose hash changes is drift and is
// reported; re-vendoring is the correct fix, not hand-editing vendor/.
//
// `--write` regenerates the baseline. Run it only immediately after a
// deliberate re-vendor, and review the diff.
//
// Usage:
//   dart run tool/check_drift.dart            # verify against baseline
//   dart run tool/check_drift.dart --write    # regenerate baseline
import 'dart:io';

import 'package:crypto/crypto.dart';

/// Baseline manifest path, relative to repo root.
const String baselinePath = 'vendor/BASELINE.sha256';

/// Vendored subtrees that are hashed.
const List<String> vendorPackages = [
  'flutter_skill',
  'marionette_mcp',
  'marionette_flutter',
  'marionette_cli',
  'marionette_logging',
  'marionette_logger',
];

/// A single hash entry.
class HashEntry {
  const HashEntry(this.path, this.sha256);

  final String path;
  final String sha256;
}

/// Reads and writes the vendor hash baseline.
class DriftChecker {
  DriftChecker({required this.root});

  final Directory root;

  /// Computes hashes for all vendored `.dart` files, sorted by path.
  Map<String, String> computeHashes() {
    final result = <String, String>{};
    for (final pkg in vendorPackages) {
      final dir = Directory('${root.path}${Platform.pathSeparator}vendor'
          '${Platform.pathSeparator}$pkg');
      if (!dir.existsSync()) continue;

      final files = dir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

      for (final f in files) {
        final rel = _rel(f.path);
        final digest = sha256.convert(f.readAsBytesSync()).toString();
        result[rel] = digest;
      }
    }
    return result;
  }

  /// Parses the baseline file into path -> hash.
  Map<String, String> readBaseline() {
    final file = File('${root.path}${Platform.pathSeparator}$baselinePath');
    if (!file.existsSync()) return {};
    final out = <String, String>{};
    for (final line in file.readAsLinesSync()) {
      if (line.trim().isEmpty || line.startsWith('#')) continue;
      final idx = line.indexOf('  ');
      if (idx == -1) continue;
      out[line.substring(idx + 2)] = line.substring(0, idx);
    }
    return out;
  }

  /// Writes the baseline file.
  void writeBaseline(Map<String, String> hashes) {
    final file = File('${root.path}${Platform.pathSeparator}$baselinePath');
    final buffer = StringBuffer()
      ..writeln('# SHA-256 baseline of vendored Dart sources.')
      ..writeln('# Generated by tool/check_drift.dart --write after re-vendoring.')
      ..writeln('# Format: <sha256><two spaces><repo-relative path>')
      ..writeln('# Vendor sources carry ONLY the rename rewrites; any other change')
      ..writeln('# is drift and must be fixed upstream, not in place.');
    final paths = hashes.keys.toList()..sort();
    for (final p in paths) {
      buffer.writeln('${hashes[p]}  $p');
    }
    file.writeAsStringSync(buffer.toString());
  }

  /// Compares [current] against [baseline].
  DriftReport compare(Map<String, String> baseline, Map<String, String> current) {
    final report = DriftReport();
    for (final entry in baseline.entries) {
      final now = current[entry.key];
      if (now == null) {
        report.deleted.add(entry.key);
      } else if (now != entry.value) {
        report.modified.add(entry.key);
      }
    }
    for (final entry in current.entries) {
      if (!baseline.containsKey(entry.key)) {
        report.added.add(entry.key);
      }
    }
    return report;
  }

  String _rel(String path) =>
      path.startsWith(root.path) ? path.replaceAll('\\', '/').substring(root.path.length + 1) : path;
}

/// Difference between baseline and current vendor tree.
class DriftReport {
  final List<String> modified = [];
  final List<String> added = [];
  final List<String> deleted = [];

  bool get isClean => modified.isEmpty && added.isEmpty && deleted.isEmpty;

  int get total => modified.length + added.length + deleted.length;

  @override
  String toString() {
    if (isClean) return 'no drift';
    final b = StringBuffer()
      ..writeln('DRIFT DETECTED: $total file(s) differ from baseline');
    if (modified.isNotEmpty) {
      b.writeln('\nmodified (${modified.length}):');
      modified.take(20).forEach((p) => b.writeln('  M $p'));
      if (modified.length > 20) b.writeln('  ... ${modified.length - 20} more');
    }
    if (added.isNotEmpty) {
      b.writeln('\nadded (${added.length}):');
      added.take(20).forEach((p) => b.writeln('  A $p'));
      if (added.length > 20) b.writeln('  ... ${added.length - 20} more');
    }
    if (deleted.isNotEmpty) {
      b.writeln('\ndeleted (${deleted.length}):');
      deleted.take(20).forEach((p) => b.writeln('  D $p'));
      if (deleted.length > 20) b.writeln('  ... ${deleted.length - 20} more');
    }
    return b.toString();
  }
}

Future<void> main(List<String> args) async {
  final write = args.contains('--write');
  final scriptDir = File.fromUri(Platform.script).parent;
  final root = Directory('${scriptDir.path}${Platform.pathSeparator}..');

  final checker = DriftChecker(root: root);
  final current = checker.computeHashes();

  if (current.isEmpty) {
    stderr.writeln('FAILED: no vendored files found under vendor/.');
    exit(2);
  }

  if (write) {
    checker.writeBaseline(current);
    stdout.writeln('Wrote $baselinePath with ${current.length} entries.');
    return;
  }

  final baseline = checker.readBaseline();
  if (baseline.isEmpty) {
    stderr.writeln('FAILED: $baselinePath missing or empty.\n'
        'Run: dart run tool/check_drift.dart --write');
    exit(2);
  }

  final report = checker.compare(baseline, current);
  stdout.writeln('checked ${current.length} vendored files '
      'against ${baseline.length} baseline entries');
  stdout.writeln(report);

  if (!report.isClean) {
    stderr.writeln('\nVendor drift is a bug: re-vendor from upstream instead of '
        'editing vendor/ by hand.');
    exit(1);
  }
  stdout.writeln('\nOK: vendor tree matches baseline.');
}
